const mongoose = require("mongoose");

const applicationSchema = new mongoose.Schema({
    firstName:{
      type:String,
      trim:true  
    },
    lastName:{
        type:String,
        trim:true
    },
    dateOfBirth:{
        type:Date,
        trim:true
    },
    sex:{
        type:String,
        trim:true
    },
    address:{
        type:String,
        trim:true
    },
    religion:{
        type:String,
        trim:true
    },
    fathersFirstName:{
        type:String,
        trim:true
    },
    fathersLastName:{
        type:String,
        trim:true
    },
    fathersEmail:{
        type:String,
        unique:true
    },
    fathersPhone:{
        type:String,
        trim:true
    },
    fathersNID:{
        type:String,
        trim:true
    },
    fathersDOB:{
        type:Date,
        trim:true
    },
    fathersMaritalStatus:{
        type:String,
        trim:true
    },
    fathersOccupation:{
        type:String,
        trim:true
    },
    fathersAddress:{
        type:String,
        trim:true
    },
    fathersReligion:{
        type:String,
        trim:true
    },
    mothersFirstName:{
        type:String,
        trim:true
    },
    mothersLastName:{
        type:String,
        trim:true
    },
    mothersEmail:{
        type:String,
        unique:true
    },
    mothersPhone:{
        type:String,
        trim:true
    },
    mothersNID:{
        type:String,
        trim:true
    },
    mothersDOB:{
        type:Date,
        trim:true
    },
    mothersMaritalStatus:{
        type:String,
        trim:true
    },
    mothersOccupation:{
        type:String,
        trim:true
    },
    mothersAddress:{
        type:String,
        trim:true
    },
    mothersReligion:{
        type:String,
        trim:true
    }

});

module.exports = mongoose.model("Application", applicationSchema)